### ISSUE TITLE
Cannot install on Ubuntu

### ISSUE THREAD

**Issue by 29axe** [zhgzhg/Geany-JSON-Prettifier#1]
Couldn't install this plugin.
At first I had to install 'libgtk2.0-dev' in order to run command `make` successfuly (this should be indicated in README)
So I installed it with command: `sudo apt-get install libgtk2.0-dev`

Then I had this issue when running `sudo make install`:

> rm -f /usr/lib64/geany/jsonprettifier.*
> rm -f /usr/lib64/geany/json_prettifier.\*  
> cp -f ./jsonprettifier.so /usr/lib64/geany
> cp: cannot create regular file '/usr/lib64/geany': No such file or directory
> Makefile:22: recipe for target 'startinstall' failed
> make: **\* [startinstall] Error 1

I have no idea what to do about that error and I have to give up.. :(

**Comment by zhgzhg** [comment]
Thanks for the feedback!
I have updated the dependencies list.
The installation under Ubuntu should be fixed now.

**Comment by 29axe** [comment]
Thanks. Will try that when I have time :)

**Comment by dominique-jocal-cbp** [comment]
Hello zhgzhg, 
on an ubuntu 18, the compilation failed because of another missing dependency;
`pkg-config --cflags geany`
returned
```
Package gtk+-3.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `gtk+-3.0.pc'
to the PKG_CONFIG_PATH environment variable
Package 'gtk+-3.0', required by 'geany', not found
```
preventing `geanyplugin.h` to be resolved;

it was resolved by adding 
`sudo apt install libgtk-3-dev`

thank you a lot for your plugin, very useful!
Dominique.

**Comment by zhgzhg** [comment]
Thanks for the the notes! I've updated the README.md accordly. 
I am glad that the plugin does the job for you!
