### ISSUE TITLE
Geany 2.x Support

### ISSUE THREAD

**Issue by own3mall** [zhgzhg/Geany-JSON-Prettifier#12]
With Geany 2.0, the plugin no longer works out of the box.

`jsonprettifier_x86_64.dll is not binary compatible with this release of Geany - please recompile it.` 

If this requires more than renaming (Geany only supports 64 bit with v2 now), could you please release a new version intended for 2.x releases but still keep the older version available for 1.x releases as well?

**Comment by zhgzhg** [comment]
Thanks for bringing this up, @own3mall .
I am looking into it..

**Comment by zhgzhg** [comment]
@own3mall , finally I have recompiled the plugin for Geany 2.0.
The new DLL is added to the [Releases](https://github.com/zhgzhg/Geany-JSON-Prettifier/releases) artifacts.

**Comment by own3mall** [comment]
Thank you, it works great!
