### ISSUE TITLE
Indenting Preference

### ISSUE THREAD

**Issue by sagarchalise** [zhgzhg/Geany-JSON-Prettifier#2]
I think the indent preference should be taken from filetype configuration or geany configuration if available. It would also be nice to have indent preference entry.

**Comment by zhgzhg** [comment]
Hi and thanks for suggesting this!
I am definitely going to add it in the next release. Until then I'd suggest to use as a "temporary" solution the existing search & replace functionality.

**Comment by jguglev** [comment]
Ability to choose between spaces and tabs + their exact count is available in release [v1.5](https://github.com/zhgzhg/Geany-JSON-Prettifier/releases/tag/v1.5).
