### ISSUE TITLE
Error in make localinstall

### ISSUE THREAD

**Issue by macktab** [zhgzhg/Geany-JSON-Prettifier#5]
There is error in make localinstall command
```
rm -f /home/maktub/.config/geany/plugins/jsonprettifier.so
cp -f ./jsonprettifier.so /home/maktub/.config/geany/plugins
chmod 755 /home/maktub/.config/geany/plugins/jsonprettifier.so
chmod: cannot access '/home/maktub/.config/geany/plugins/jsonprettifier.so': Not a directory
make: *** [Makefile:42: localinstall] Error 1
```

**Comment by zhgzhg** [comment]
Thanks for reporting the issue @macktab!
It seems that $HOME/.config/geany/plugins directory is missing and the cp command might have placed "jsonprettifier.so" file in "/home/maktub/.config/geany" with the name "plugins" instead. I'll investigate further on that.

Meanwhile as a quick workaround I'd suggest checking whether "/home/maktub/.config/geany/plugins" exists as a directory and creating it if is missing. Then `make localinstall` should work.

**Comment by zhgzhg** [comment]
In addition, on some environments the plugin directory can be missing despite the presence of Geany. As an extra measure localinstall now attempts creating the directory beforehand.
