### ISSUE TITLE
make intall fails on Raspberry Pi [workaround]

### ISSUE THREAD

**Issue by ScaroDj** [zhgzhg/Geany-JSON-Prettifier#9]
Hello! 

Just wanted to document that after successfully building the plugin with "make", "make install" fails with the following output: 

```
rm -f "/geany/jsonprettifier.so"
rm -f /geany/jsonprettifier.*
rm -f /geany/json_prettifier.*
cp -f ./jsonprettifier.so "/geany/jsonprettifier.so"
cp: cannot create regular file '/geany/jsonprettifier.so': No such file or directory
make: *** [Makefile:38: globalinstall] Error 1
```

I simply created the directory and copied the file 

```
pi@raspberrypi:~ $ sudo mkdir /usr/lib/geany
pi@raspberrypi:~ $ sudo cp ./jsonprettifier.so /usr/lib
```

You might want to fix it or people could just use this workaround. 

Thanks!

**Comment by zhgzhg** [comment]
Thanks for reporting the issue! The Makefile was not handling installation directory detection under Raspbian.  I've edited it accordingly, and I've also improved the README instructions to make it more clear that `make install` requires root privileges.
